### ISSUE TITLE
isEdgeCaseWithOneOrZeroChars?

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [aceakash/string-similarity#13]
Hi :)

Just finished modifying this script so that I can use it in mongoDB (SpiderMonkey with some parts of ES6) without the lodash dependency, and noticed this unused method, `isEdgeCaseWithOneOrZeroChars`. 

It was [introduced here](https://github.com/aceakash/string-similarity/commit/013ac3a839c96daba82dc7ab10ee9548899ecc7d#diff-32ab056f3eb93936bae4f74fd73913ee), but that's over a year ago, and it hasn't been used since then.

So I'm wondering if it's some unfinished work that should be there, or just some a stab at some approach deemed unnecessary and then accidentally left behind?

Cheers! :)

Daniel

**Comment by aceakash** [comment]
Thanks @DanielSmedegaardBuus 
Fixed and released in https://github.com/aceakash/string-similarity/releases/tag/1.2.2
