### ISSUE TITLE
Issue comparing a word against a the same word plus a blank and another letter

### ISSUE THREAD

**Issue by andresarroyave** [aceakash/string-similarity#16]
Hello, I found an issue comparing a word against a the same word plus a blank and another letter. 
Eg:
"Iphone" compared with "Iphone X" gives me a match of 1, but the texts are not equal. It should be close to 1 but not 1.

I'm using version 2.0.0

findBestMatch('Iphone', ['Iphone 8', 'Iphone 10', 'Iphone X', 'Iphone XS'])
![image](https://user-images.githubusercontent.com/39885574/46635017-9983b780-cb18-11e8-9553-1b05825065ba.png)

**Comment by RajRohitCode** [comment]
> Hello, I found an issue comparing a word against a the same word plus a blank and another letter.
> Eg:
> "Iphone" compared with "Iphone X" gives me a match of 1, but the texts are not equal. It should be close to 1 but not 1.
> 
> I'm using version 2.0.0
> 
> findBestMatch('Iphone', ['Iphone 8', 'Iphone 10', 'Iphone X', 'Iphone XS'])
> ![image](https://user-images.githubusercontent.com/39885574/46635017-9983b780-cb18-11e8-9553-1b05825065ba.png)
![image](https://user-images.githubusercontent.com/41776959/48538024-510aa700-e8d9-11e8-8bfa-5abbad56d875.png)
It's a major bug.

**Comment by RajRohitCode** [comment]
![image](https://user-images.githubusercontent.com/41776959/48538144-a8a91280-e8d9-11e8-823d-a584e2d31c3c.png)
It's not matching to expected string.

**Comment by aceakash** [comment]
Fixed in [3.0.0](https://github.com/aceakash/string-similarity/releases/tag/3.0.0)
