### ISSUE TITLE
Weird result based on string case

### ISSUE THREAD

**Issue by Vadorequest** [aceakash/string-similarity#22]
I've tried to compare the strings, as follow:

`stringSimilarity.findBestMatch('bnp', ['BNP Paribas', absolutelyunrelated])`

>Both `rating` are 0

`stringSimilarity.findBestMatch('BNP', ['BNP Paribas', absolutelyunrelated])`

> BNP Paribas rating is 0.36363636363636365

I wouldn't expect 0 with `bnp`, I'd expect something around 0.2+ I guess, the difference is huge based on the string case.

**Comment by aceakash** [comment]
Hi @Vadorequest, the comparison is case-sensitive by design. If you want case-insensitive comparison, please convert all your inputs to uppercase or lowercase before comparing.
