### ISSUE TITLE
Why is Sørensen–Dice coefficient better?

### ISSUE THREAD

**Issue by adyavanapalli** [aceakash/string-similarity#27]
> Finds degree of similarity between two strings, based on Dice's Coefficient, _**which is mostly better than Levenshtein distance**_.

What's the rationale behind this claim?

**Comment by aceakash** [comment]
Completely subjective, but see https://github.com/aceakash/string-similarity/issues/25#issue-396265363 for an example

**Comment by igorcosta** [comment]
I don't think so. The accuracy or distance similarity is very partial when presented against two distinct topics.
