### ISSUE TITLE
Memoize results

### ISSUE THREAD

**Issue by DavideCarvalho** [aceakash/string-similarity#28]
It will be good if you memoize the result, so if you run the function with the same arguments, it will give the result right away instead of making the calculation all over again

**Comment by DavideCarvalho** [comment]
Integration with external cache mechanisms sounds interesting too, but memoizing is memory only - AFAIK -. Maybe would be good creating another issue to integrate with other types of cache, like redis

**Comment by aceakash** [comment]
Is performance a problem? I'm happy to look at optimisations if I get enough reports about slowness
