### ISSUE TITLE
Soporte para Español?

### ISSUE THREAD

**Issue by Oxicode** [aceakash/string-similarity#29]

**Comment by DavideCarvalho** [comment]
I don't know with this would be good. The calculation must be really slow using only english, using other languagues would just make it slower.
To make it faster, maybe the api should have the option to be used something like ```new stringSimilarity('SPANISH')```, and after that it will only tell the similarity to spanish words.

**Comment by Oxicode** [comment]
i like ```new stringSimilarity('SPANISH')```

**Comment by aceakash** [comment]
Sorry, no plans for this in the near future.
