### ISSUE TITLE
How is similarity calculated

### ISSUE THREAD

**Issue by 18672786357** [aceakash/string-similarity#34]
How is similarity calculated？

**Comment by 18672786357** [comment]
return (2.0 * intersectionSize) / (first.length + second.length - 2);，，，，Why is this line of code minus 2

**Comment by dangh** [comment]
Hey @18672786357 It's 6 months old and you might found the answer yourself but I like to post my answer here for the future me 😛 

The [Sørensen–Dice algorithm](https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient#Formula) is calculate the number of matching items in 2 sets using the formular `DSC = 2(𝚇⋂𝚈)/(|𝚇|+|𝚈|)` where `|𝚇|` and `|𝚈|` are the number of items in each set.

This library convert each strings to multiple bigrams (2 characters substring) and apply the formular above. If you break the string manually you will see that the number of items is the length of string minus 1.
```js
"abide" -> ['ab', 'bc', 'cd', 'de']
```

We have two strings so `|𝚇|+|𝚈|` will be `(s1.length - 1) + (s2.length - 1)`. That's where the number 2 come from.

**Comment by Rabbitzzc** [comment]
```js
let str = '12345'  // len = 5
let set = {'12', '23', '34', '45'} len =4
// so one string represents the denominator that needs to:
X = len - 1 = str.length - 1
```

**Comment by zscaiosi** [comment]
> Hey @18672786357 It's 6 months old and you might found the answer yourself but I like to post my answer here for the future me stuck_out_tongue
> 
> The [Sørensen–Dice algorithm](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient#Formula) is calculate the number of matching items in 2 sets using the formular `DSC = 2(𝚇⋂𝚈)/(|𝚇|+|𝚈|)` where `|𝚇|` and `|𝚈|` are the number of items in each set.
> 
> This library convert each strings to multiple bigrams (2 characters substring) and apply the formular above. If you break the string manually you will see that the number of items is the length of string minus 1.
> 
> ```js
> "abide" -> ['ab', 'bc', 'cd', 'de']
> ```
> 
> We have two strings so `|𝚇|+|𝚈|` will be `(s1.length - 1) + (s2.length - 1)`. That's where the number 2 come from.

@dangh the bigrams are applied to the Map structure (firstBigram), not to the variables _first_ and _second_ !
first.substring(i, i + 2); **and** second.substring(i, i + 2); **_DO NOT_** modify the objects (strings), but return new strings (substrings).

It does not make any sense to subtract 2!

**Comment by aceakash** [comment]
@dangh has the right explanation and the [link](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient#Formula) that I used the formula from.
The result is as expected, 'night' and 'nacht' are similar to a degree of 0.25
https://jsbin.com/kidibosato/edit?js,console
