### ISSUE TITLE
Does not seem to care about the order of words

### ISSUE THREAD

**Issue by jessereitsma** [aceakash/string-similarity#36]
I have the following two strings:
```grid styling xs 1/12```
```grid styling xs 2/12```

And my search input is 
```
xs 2
```
Both strings get the exact same score, which doesn't seem right.
Because the xs 2 has a longer "direct match" in the order of words with the second string than the first one.
The first string only gets the same score because there is also a "2" in the string. But it's on a location that shouldn't influence the score as match as the "2" in the "right spot"

**Comment by faizanu94** [comment]
Hi Jesse,

Would you please provide a test case for your scenario, I'm getting **grid styling xs 2/12** as most relevant search result with highest score.

**Comment by faizanu94** [comment]
**Hi Jesse,**

Would you please provide a test case for your scenario? I'm getting grid styling xs 2/12 as most relevant search result with highest score.

**Comment by aceakash** [comment]
In my testing, they get different scores, with xs 2/12 as more relevant.
https://repl.it/repls/RectangularWarmheartedTitle
