### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by dhilt** [aceakash/string-similarity#38]
IE doesn't understand ES6 (const, let and arrow functions are the ES6 things that I see in the package sources) and to provide IE compatibility (curse him) we need to have our vendor bundles in ES5. And it's not easy to transpile a specific library during bundling...

The common way is to have ./dist/compare-strings.js in the npm package repo and an npm build script for ES6 -> ES5 transpilation process. If it's ok, I can provide a PR covering this situation. What do you think?

**Comment by ebitauld** [comment]
Also get an issue with this library and IE11:
![image](https://user-images.githubusercontent.com/14015828/56736247-f585f480-6767-11e9-8d38-cff9764e0376.png)

**Comment by ludo97240** [comment]
Replace the index.js file by the one in this archive : 

[index.zip](https://github.com/aceakash/string-similarity/files/4787265/index.zip)


Maybe a pull request can be done to fix it definitively

**Comment by CMadden8** [comment]
I'm also getting this issue in IE11, it's preventing log in to the application. If the patch could be applied to the module that would really help...
