### ISSUE TITLE
compareTwoStrings return wrong output

### ISSUE THREAD

**Issue by kishanmundha** [aceakash/string-similarity#46]
I notice that if we pass `ababacac` and `abacabac` in `compareTwoStrings`, it return output `1` which is wrong.

```
var stringSimilarity = require('string-similarity');
console.log(stringSimilarity.compareTwoStrings('ababacac', 'abacabac'));
```

**Expected**
Should not `1`

**Output**
`1`

**Comment by semmel** [comment]
> I notice that if we pass ababacac and abacabac in compareTwoStrings, it return output 1 which is wrong.

It's not wrong, it's just that Sørensen–Dice is abused here for strict string comparison. The first sentence in [Wikipedia](https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient) makes it clear: 

> The Sørensen–Dice coefficient is a statistic used to gauge the similarity of two samples.

It's in the nature of "statistics" to be blurry.

More fun examples:
```javascript
stringSimilarity.compareTwoStrings('abaa', 'baab'); // 1
stringSimilarity.compareTwoStrings('baab', 'aaba'); // 1
stringSimilarity.compareTwoStrings('aaba', "abaa"); // 1
```
