### ISSUE TITLE
Is it possible to import it in a ES6 module ? (front-side)

### ISSUE THREAD

**Issue by nathanschwarz** [aceakash/string-similarity#47]
I'm trying to use the package to implement a fuzzy search in a React component.
I don't want to use UMD.

I'm trying to import the module like so:

`import stringSimilarity from 'stringSimilarity'`

Node throw: `Cannot find module 'stringSimilarity'.`

Is it possible with this package ?

**Comment by chengsam** [comment]
`import stringSimilarity from 'string-similarity'`
