### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by jfmmm** [aceakash/string-similarity#5]
Hi,

I'm having a weird result when comparing those two string.
It always return a rating of 0 despite them having 2 letters in common.

stringSimilarity.compareTwoStrings('NOS', 'NPS')
//0

stringSimilarity.findBestMatch('NOS', ['NPS'])
//{ ratings: [ { target: 'NPS', rating: 0 } ], bestMatch: { target: 'NPS', rating: 0 } }

https://runkit.com/588655d7fb7a220014a01b47/5886577d0629220014e341d7

Thanks.

**Comment by aceakash** [comment]
That's how the algorithm works - 
NOS is split into two bigrams NO and OS
NPS is split similarly into NP and PS
There are no common bigrams, hence similarity is 0

Further reading: https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient#Formula

**Comment by jfmmm** [comment]
Ah I guess I should have read more on the algoritm.

I ended up using this instead and it did what I wanted.
https://www.npmjs.com/package/leven

Thanks for the answer.
