### ISSUE TITLE
Handling of tiny strings not functioning as expected

### ISSUE THREAD

**Issue by Jezternz** [aceakash/string-similarity#6]
For some reason when both strings are 1 or less characters long, compareTwoStrings will return Number.NaN instead of expected 1 or 0.

Examples:
```
compareTwoStrings("", "") === Number.NaN
compareTwoStrings("a", "a") === Number.NaN
compareTwoStrings("a", "") === Number.NaN
compareTwoStrings("aa", "aa") === 1
compareTwoStrings("aa", "") === 0
```

This is a problem as Number.NaN is always greater then other numbers,
eg the following will always return false, even though expected true:
`compareTwoStrings("", "") > 0.9`

I have temporarily got around this in my own project, by simply using:
```
if(a.length <= 1 && b.length <= 1)return a === b ? 1 : 0;
return compareTwoStrings(a, b);
```

Cheers,
Josh

**Comment by felixfbecker** [comment]
I have the same problem, for two empty (and therefor identical) strings it returns `NaN` instead of `1`.

**Comment by aceakash** [comment]
@felixfbecker @Jezternz thanks for reporting, fixed in 1.2.0

**Comment by joaomilho** [comment]
Well, even though `compareTwoStrings('h', 'h')` is fixed (returns 1), it still seems incorrect:

```
compareTwoStrings('h', 'hm') // 0
```

**Comment by aceakash** [comment]
This library implements the [Sørensen–Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient) algorithm. It doesn't work for very small strings.

**Comment by joaomilho** [comment]
fair enough :D
