### ISSUE TITLE
Wrong bestMatch with game titles

### ISSUE THREAD

**Issue by TheTimmaeh** [aceakash/string-similarity#8]
Hey there!

I've noticed that string-similarity is having issues with game titles. Here's a little example:

`var matches = stringSimilarity.findBestMatch('Portal 2', ['Portal', 'Portal 2']);`

This example returns 'Portal' as bestMatch. However if I change the order of the targetStrings array, like this:

`var matches = stringSimilarity.findBestMatch('Portal 2', ['Portal 2', 'Portal']);`

Then bestMatch is Portal 2. While this sounds like the solution, searching Portal would lead to bestMatch = Portal 2.

Testing around I also found out that if I compareTwoStrings('Portal', 'Portal 2'), the return value is 1, even tho those 2 strings are obviously not exactly the same?

Is there any way to make the comparison more strict?

**Comment by TheTimmaeh** [comment]
I've decided to fetch all best matches via

`var bestMatches = _filter(matches.ratings, {'rating': matches.bestMatch.rating});`

and compare these via https://www.npmjs.com/package/leven to get a more accurate result.

**Comment by aceakash** [comment]
Yup, this is a shortcoming of this algorithm - https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient
