### ISSUE TITLE
is it possible to support chinese?

### ISSUE THREAD

**Issue by jackyon** [aceakash/string-similarity#9]
I have test string-similarity with chinese letter, but seems not working, it appears "0"

`var similarity = stringSimilarity.compareTwoStrings('布莱顿', '布赖顿');`

plz advise. thx.

**Comment by zac1st1k** [comment]
stringSimilarity.compareTwoStrings('布 莱 顿', '布 赖 顿');

returns `NaN`

**Comment by zac1st1k** [comment]
This is desired. three letters/漢字 with a unmatched letter/漢字 in middle is 0 Sørensen–Dice coefficient by definition.

You could try `ABC` vs `ACC`. It also 0 similarity.
