### ISSUE TITLE
Matching % seems incorrect

### ISSUE THREAD

**Issue by oom-** [aceakash/string-similarity#91]
I just tryed the example: 
```js
stringSimilarity.compareTwoStrings("healed", "sealed");
//0.8
```
=> **80%** for a 1 letter change.
```js
stringSimilarity.compareTwoStrings("healed", "ehaled");
//0.6
```
=> **60%** for 2 letter switching

Ok I get it but now I just try with another word that contains 1 letter less (5 char length vs 6)

```js
stringSimilarity.compareTwoStrings("fuira", "fuia");
//0.57
```
=> **57%** for a 1 letter change (just lost 23%)

```js
stringSimilarity.compareTwoStrings("furia", "fuira");
//0.25
```
=> **25%** for a 1 letter change (just lost 35%)

Seems to me that less the string is long more the matching is severe.
Is there a way to make it "average" undepending of the length ?

**Comment by aceakash** [comment]
@oom- Different algorithms will have different trade-offs. This library implements the [Sørensen–Dice_coefficient](https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient) as the similarity score. I would encourage you to try out other string comparison algorithms to see which one best fits your needs. [This](https://stackoverflow.com/questions/3576211/string-similarity-algorithms) might be a good starting point.
